
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Get latest cloud-init version
      run: |
        LATEST_VERSION=$(curl -s https://pypi.org/pypi/cloud-init/json | jq -r .info.version)
        echo "Latest cloud-init version is $LATEST_VERSION"
        echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV

    - name: Update requirements.txt with latest cloud-init version
      run: |
        sed -i "s/cloud-init==LATEST_VERSION/cloud-init==$LATEST_VERSION/" requirements.txt
        cat requirements.txt  # Display the updated requirements.txt for debugging

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle src/

    - name: Run tests
      run: |
        # Add tests here eg pytest
        pip Install pytest
        pytest tests/
